### ISSUE TITLE
Implement Put/Update

### ISSUE THREAD

**Issue by ardalis** [ardalis/DotNetDataAccessTour#1]
If someone wants to add Update support in the Put method of the 5 different controllers that would be helpful.

For now it can just update the Author's Name column.

**Comment by radekwojpl2** [comment]
I can take care of it :)

**Comment by ardalis** [comment]
Go for it, @radekwojpl2 . Thanks!

**Comment by radekwojpl2** [comment]
Here is PR https://github.com/ardalis/DotNetDataAccessTour/pull/2
